language: bash
sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker build -t pupillabs/pupil-labs-website-node .
  - docker run -d pupillabs/pupil-labs-website-node
  - docker ps -a

after_success:
  - sh .travis/deploy_dockerhub.sh
